# Generated by Django 5.1 on 2024-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='uploads/products/'),
        ),
    ]
